substitutions:
  name: esp32-bluetooth-proxy-cbd1d4
  friendly_name: Bluetooth Proxy cbd1d4

packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic-s3.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret esp32_bluetooth_proxy_cbd1d4__encryption_key
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# ============================================================
# RESTART BUTTON
# ============================================================

button:
  - platform: restart
    name: "Restart ESP32"
    icon: "mdi:restart"